### ISSUE TITLE
LSP4J issue on Windows and Linux

### ISSUE THREAD

**Issue by colameo** [jhipster/jhipster-ide#201]
The selected wizard could not be started.
org/eclipse/lsp4j/RenameParams (occurred in io.github.jhipster.jdl.ui.JDLExecutableExtensionFactory)
org/eclipse/lsp4j/RenameParams

**Comment by colameo** [comment]
fixed

**Comment by thomasdgithub** [comment]
I am still having this bug when I try to open the Wizzard.

The selected wizard could not be started.
org/eclipse/lsp4j/RenameParams (occurred in io.github.jhipster.jdl.ui.JDLExecutableExtensionFactory)
org/eclipse/lsp4j/RenameParams

Jhipster Plugin: 1.4.0
Eclipse Version: Photon Release (4.8.0)

**Comment by colameo** [comment]
thanks for reporting! As you can see, it was fixed... however, I know where the problem is and will have a look.

**Comment by colameo** [comment]
...hm, I just tried with a fresh eclipse photon distro on Windows 10 and it works. 
Have you upgraded from the old version or installed the new version again?

**Comment by colameo** [comment]
can you also check which lsp4j version is installed in you distro?

![screen shot 2018-09-21 at 12 14 02](https://user-images.githubusercontent.com/629760/45875416-e9802180-bd97-11e8-8a82-586ca4a31cce.png)

**Comment by thomasdgithub** [comment]
Hi Serano, 

I reinstalled JHipster - Plugin from the Eclipse Marketplace, but the Problem still exists.

My lsp4j Version: 0.4.1v20180515-1312
My System: Windows 10

Thank you for your help.

Regards Thomas

**Comment by colameo** [comment]
0.4.1 is the wrong version. Looks like you have installed Xtext 2.14, haven't you?

**Comment by carloca68** [comment]
Hi Serano, I'm having the same problem with Spring Tool Suite, both 3.8 and the new 4.0 versions.

> The selected wizard could not be started.
> org/eclipse/lsp4j/RenameParams (occurred in io.github.jhipster.jdl.ui.JDLExecutableExtensionFactory)
> org/eclipse/lsp4j/RenameParams

How can I have the correct version?
I would love to use your plugin but this problems with eclipse deps are really annoying, thank you for committing your time to this project. 
Eclipse really sucks with this mad dependencies issues, it's one of the reasons I moved to Intellij, i'm using eclipse just for tools have no support on Intellij :-(

**Comment by carloca68** [comment]
> 
> 
> Hi Serano, I'm having the same problem with Spring Tool Suite, both 3.8 and the new 4.0 versions.
> 
> > The selected wizard could not be started.
> > org/eclipse/lsp4j/RenameParams (occurred in io.github.jhipster.jdl.ui.JDLExecutableExtensionFactory)
> > org/eclipse/lsp4j/RenameParams
> 
> How can I have the correct version?
> I would love to use your plugin but this problems with eclipse deps are really annoying, thank you for committing your time to this project.
> Eclipse really sucks with this mad dependencies issues, it's one of the reasons I moved to Intellij, i'm using eclipse just for tools have no support on Intellij :-(

**Comment by carloca68** [comment]
Don't worry dude,

Resolved my problem installing another eclipse just for it and using a different workplace.
The plugin is working fine with the version below, thank you.

> Eclipse IDE for Java Developers
> 
> Version: 2018-09 (4.9.0)
> Build id: 20180917-1800

**Comment by colameo** [comment]
@carloca68, I'm working to fix this issue in the next version 1.5.0 of JHipster IDE.
